### PR TITLE
#23 add reference genome parsing, downgrade python for pyfasta, fix typo

### PR DESCRIPTION
**Pull request by LiineKasak**
Notable things:
- download this file into data folder: `https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/hg38/hg38.fa`
- python downgraded due to pyfasta error with 3.10.0

Otherwise, think this is the best way to load sequence, afterwards can add logic due to window and other shifts

### CODE REVIEW

**Review by TaoDFang — COMMENTED** [review]
for function  get_sequence() , i can understand what does it do . 
while better to add some documentation ?

For the one hot hot encoding . just curious how many nucleotides in sequences are actually "N"

**Comment by LiineKasak** [comment]
thought a oneliner function doesn't need documentation, but I'll add it for good measure :)
there are a lot of Ns in the ref sequence, typically at the start and end of chromosomes I think. for example the first 10 000 nucleotides in chr1 are Ns iirc. But for the given genes I doubt there will be any Ns. Just added encoding for it in case

**Review by TaoDFang — APPROVED** [review]

**Review by Sum02dean — APPROVED** [review]
Looks good. What is the name of the documentation you use? Is it "type hinting"? I have never used it, but see it around on github.

**Comment by LiineKasak** [comment]
@Sum02dean I just use the built in auto generation of docstring stubs in pycharm (jetbrains premium for all uni students). this is how it works: https://www.jetbrains.com/help/pycharm/using-docstrings-to-specify-types.html

**Pull request merged**
