### PR TITLE
Loading data by chromosomes

### PR DESCRIPTION
**Pull request by LiineKasak**
Added gene info and labels loading by list of chromosome numbers.

### CODE REVIEW

**Review by Sum02dean — APPROVED** [review]
Looks good to me 🤙

**Comment by TaoDFang** [comment]
Looks good for me. But i will approved it later as I want to learn how to use PR in more standard way : ).   I want  discuss where to put data and code; for example, should we use same script for utilities codes ?

**Comment by LiineKasak** [comment]
> Looks good for me. But i will approved it later as I want to learn how to use PR in more standard way : ). I want discuss where to put data and code; for example, should we use same script for utilities codes ?

@TaoDFang We should all use the same utility functions - less duplication and then we're sure that we're on the same page and there are no mistakes in our results just because we're using different base functions.

**Comment by TaoDFang** [comment]
> 

cool. Just wandering , if two people work simultaneously and create own base functions. How could they solve such conflicts ? I guess one person  has to adapt  other person's code ?  sorry for dummy question, just want to be proper coder hh

**Comment by TaoDFang** [comment]
> > Looks good for me. But i will approved it later as I want to learn how to use PR in more standard way : ). I want discuss where to put data and code; for example, should we use same script for utilities codes ?
> 
> @TaoDFang We should all use the same utility functions - less duplication and then we're sure that we're on the same page and there are no mistakes in our results just because we're using different base functions.

@LiineKasak  cool. Just wandering , if two people work simultaneously and create their own base functions. How could they solve such conflicts ? I guess one person has to adapt other person's code ? sorry for dummy question, just want to be proper coder hh

**Comment by LiineKasak** [comment]
@TaoDFang I guess either adapt or propose a better solution and then agree on an efficient way of solving the problem. that's why I'm trying to get some base things into main fast - we should be working on the same version of things.

For now, if we agree that these base functions are okay, then we can add it to main.
If you want to improve this in some way, make an issue for the problem, and then make a PR so we can all adapt to your improved method :)
And if you have or want to make other base methods we would need, follow the same procedure

**Comment by TaoDFang** [comment]
> @TaoDFang I guess either adapt or propose a better solution and then agree on an efficient way of solving the problem. that's why I'm trying to get some base things into main fast - we should be working on the same version of things.
> 
> For now, if we agree that these base functions are okay, then we can add it to main. If you want to improve this in some way, make an issue for the problem, and then make a PR so we can all adapt to your improved method :) And if you have or want to make other base methods we would need, follow the same procedure

sound great !

**Pull request merged**
